### ISSUE TITLE
Sometimes getting "app.address is not a function"

### ISSUE THREAD

**Issue by yuklai** [mtbrault/nextjs-http-supertest#10]
is there anything I need to do to wait for the server to finish starting before I can use it?

**Comment by yuklai** [comment]
I think the reason is I'm adding .test.ts to the same directories as the API and caused this lib to be confused. If the file ends with .test.ts/js, it might be good to skip those files when buliding the server.

**Comment by mtbrault** [comment]
Hello,

Yes indeed, I was expecting that the tests files would be outside the `pages` directory.
I will make an update for this

**Comment by mtbrault** [comment]
The fix is now available in the latest version of the package on npm

**Comment by yuklai** [comment]
Thank you for the quick fix!!
