### ISSUE TITLE
Is there a plan to add support for App Router based routes ? 

### ISSUE THREAD

**Issue by h1zqeel** [mtbrault/nextjs-http-supertest#14]

**Comment by mtbrault** [comment]
Hello,

I’m sorry but for the moment it is not planned until app directory stop being an experimental feature

**Comment by h1zqeel** [comment]
> Hello,
> 
> 
> 
> I’m sorry but for the moment it is not planned until app directory stop being an experimental feature

App directory is stable as of version 13.4 of NextJS
