### ISSUE TITLE
bug: TypeError: pageExtensions is not iterable

### ISSUE THREAD

**Issue by mnahkies** [mtbrault/nextjs-http-supertest#19]
#18 (released in `1.0.14`) starts reading `pageExtensions` from `next.config.js`

https://github.com/mtbrault/nextjs-http-supertest/pull/18/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R17

This assumes that all `next.config.js` files set a `pageExtensions` override, but it's an optional configuration property:

type: https://github.com/vercel/next.js/blob/b559c282c2d73a0f67816d39f6468b29ae9bc641/packages/next/src/server/config-shared.ts#L726
validation: https://github.com/vercel/next.js/blob/b559c282c2d73a0f67816d39f6468b29ae9bc641/packages/next/src/server/config-schema.ts#L590
default: https://github.com/vercel/next.js/blob/b559c282c2d73a0f67816d39f6468b29ae9bc641/packages/next/src/server/config-shared.ts#L980

this later results in an error like:
```
TypeError: pageExtensions is not iterable
```

when importing `nextjs-http-supertest`

This also won't work if the config is exported as a function, or async function (ref: https://nextjs.org/docs/pages/api-reference/next-config-js). I imagine it additionally wouldn't work if using a `next.config.mjs` file.

**Suggested resolution**
I'm not sure if next exposes a public API to get the resolved config, but I think it would be preferable to use one if possible. 

I believe the internal API is `loadConfig` here (which may still be preferable over trying to re-implement it's config resolution in this package), https://github.com/vercel/next.js/blob/b559c282c2d73a0f67816d39f6468b29ae9bc641/packages/next/src/server/config.ts#L918

**Comment by mtbrault** [comment]
Hello,

This new commit is available on version 1.0.15, hopping that it will fix your issue.

https://github.com/mtbrault/nextjs-http-supertest/commit/048604334781f24d31a3fcf8f5b40fa30858ed66
