### ISSUE TITLE
Latest commit breaks route resolution

### ISSUE THREAD

**Issue by justin-caldicott** [mtbrault/nextjs-http-supertest#3]
The [latest commit](https://github.com/mtbrault/nextjs-http-supertest/commit/af166dcf70bfe3c1e832c1863abce439e4af9a51#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R21), which has not been published to npm, breaks route resolution, as switching to foreach means nothing is returned from `getDynamicRoute` itself.

**Comment by mtbrault** [comment]
Fixed
