### ISSUE TITLE
No tests

### ISSUE THREAD

**Issue by justin-caldicott** [mtbrault/nextjs-http-supertest#6]
There are currently no tests of this implementation. Ideally, a simple nextjs app would be tested via supertest.

I believe this would have caught the [latest regression](https://github.com/mtbrault/nextjs-http-supertest/issues/3). It would also be nice to be able to extend the tests for regressions as issues are resolved.

**Comment by mtbrault** [comment]
Yes i know and I planned to test a basic nextjs app.
I'll try to find some time for it soon. For the moment, I've merged all your PR and published it on npm

**Comment by justin-caldicott** [comment]
Many thanks for the prompt reviews/fixes. Very helpful lib. :)
